### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by jvink** [chunkai1312/material-ui-snackbar-redux#2]
Please implement Typescript support.

`Could not find a declaration file for module 'material-ui-snackbar-redux'. 'c:/Files/Werk/hsnportal/node_modules/material-ui-snackbar-redux/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/material-ui-snackbar-redux` if it exists or add a new declaration (.d.ts) file containing `declare module 'material-ui-snackbar-redux';`

**Comment by chunkai1312** [comment]
This package has been deprecated. Please use [notistack](https://github.com/iamhosseindhv/notistack) instead.
